# Generated by Django 4.1 on 2022-08-27 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_disease_identified_by_alter_disease_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='disease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.disease'),
        ),
    ]
